apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://patricklaabs.github.io/sample-application/
    targetRevision: 1.0.3
    helm:
      releaseName: sample-application
    chart: sample-application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
