apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.39.7
    helm:
      releaseName: argo-workflows
      values: |
        workflow:
          serviceAccount:
            create: true
            name: "argocd-workflow"
          rbac:
            create: true
        controller:
          rbac:
            create: true
            accessAllSecrets: true
          workflowNamespaces:
            - argo
          workflowDefaults:
            spec:
              ttlStrategy:
                secondsAfterCompletion: 3600
        extraObjects:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: argocd-workflow-cluster
            rules:
            - apiGroups: ["cluster.x-k8s.io"]
              resources: ["clusters"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "list", "watch"]
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: argocd-workflow-cluster
            subjects:
            - kind: ServiceAccount
              name: argocd-workflow
              namespace: argo
            roleRef:
              kind: ClusterRole
              name: argocd-workflow-cluster
              apiGroup: rbac.authorization.k8s.io
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: argo-events-workflows
              namespace: argo
            rules:
            - apiGroups: ["argoproj.io"]
              verbs: ["*"]
              resources: ["workflows", "workflowtemplates"]
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: argocd-events-workflows
              namespace: argo
            subjects:
            - kind: ServiceAccount
              name: argocd-workflow
              namespace: argo
            roleRef:
              kind: Role
              name: argo-events-workflows
              apiGroup: rbac.authorization.k8s.io
        server:
          extraArgs:
          - --auth-mode=server
          - --auth-mode=client
          sso:
            enabled: false
          secure: false
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
