apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  labels:
    type: helm
spec:
  project: default
  source:
    repoURL: <REPLACE-REPO-URL>
    path: basement-deployments/components/vcluster-events
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
