apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.4.1
    helm:
      releaseName: argo-events
    chart: argo-events
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
